server:
  port: 8081

spring:
  application:
    name: auth-service
  config:
    import: configserver:http://localhost:8888
  cloud:
    config:
      name: auth-service
      profile: default
      label: main

  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/bytebites_platform_users
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# JWT Configuration
jwt:
  secret: mySecretKey1234iyahfauhiaiiyryeiyauifaidyjhy647383ahakjhfjapaadkahdkjs
  expiration: 86400000

# Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.bytebites.auth: DEBUG
    org.springframework.security: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info