server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bytebites_platform_orders
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  openfeign:
    client:
      default-config: default

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    # stream: # Remove stream config if not using RabbitMQ Streams
    #   virtual-host: /

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth/realms/bytebites

jwt:
  secret: ${JWT_SECRET:mySecretKey1234iyahfauhiaiiyryeiyauifaidyjhy647383ahakjhfjapaadkahdkjs}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  rabbitmq:
  # These are the properties used by OrderEventPublisher for exchange and routing keys
  # The actual exchange and routing key constants are defined in RabbitMQConfig.java
  # These app-level properties are more for general configuration,
  # but the RabbitMQConfig.java constants are the source of truth for bindings.
  # You can remove these if they are not directly used by any other part of the app config.
  # exchange: bytebites.exchange # This is now defined in RabbitMQConfig.ORDER_EXCHANGE
  # routingkey: bytebites.order # This is now defined in RabbitMQConfig.ORDER_ROUTING_KEY_PLACED etc.

resilience4j:
  circuitbreaker:
    instances:
      restaurant-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
  retry:
    instances:
      restaurant-service:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      show-details: always

  health:
    circuitbreakers:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.ibra.orderservice: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    feign: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
